@walletHost = http://localhost:8080

### Créer un nouveau portefeuille
POST {{walletHost}}/api/wallets
Content-Type: application/json

{
    "phoneNumber": "+221779998877",
    "email": "testclient@gmail.com",
    "initialBalance": 25000,
    "code": "WLT-TEST001",
    "currency": "XOF"
}

### Lister tous les portefeuilles (Paginé)
GET {{walletHost}}/api/wallets?page=0&size=10

### Consulter un portefeuille par numéro de téléphone
GET {{walletHost}}/api/wallets/+221779998877

### Consulter uniquement le solde
GET {{walletHost}}/api/wallets/+221779998877/balance