//j'ai pris le prot 8082 car le port 8080 est déjà utilisé par un autre processus
@walletHost = http://localhost:8082

### Créer un nouveau portefeuille
POST {{walletHost}}/api/wallets
Content-Type: application/json

{
    "phoneNumber": "+221779998877",
    "email": "testclient@gmail.com",
    "initialBalance": 25000,
    "code": "WLT-TEST001",
    "currency": "XOF"
}

POST {{walletHost}}/api/wallets/seed?numWallets=5&eventsPerWallet=0
### Lister tous les portefeuilles (Paginé)
GET {{walletHost}}/api/wallets?page=0&size=10


### Consulter un portefeuille par numéro de téléphone
GET {{walletHost}}/api/wallets/+221779998877

### Consulter uniquement le solde
GET {{walletHost}}/api/wallets/+221779998877/balance
### Créer un deuxième portefeuille
POST {{walletHost}}/api/wallets
Content-Type: application/json

{
    "phoneNumber": "+221770000002",
    "email": "client2@gmail.com",
    "initialBalance": 50000,
    "code": "WLT-TEST002",
    "currency": "XOF"
}

### Effectuer un dépôt
POST {{walletHost}}/api/wallets/1/deposit
Content-Type: application/json

{
    "amount": 10000
}

### Effectuer un retrait (frais de 1% plafonné à 5000 CFA)
POST {{walletHost}}/api/wallets/withdraw
Content-Type: application/json

{
    "phoneNumber": "+221779998877",
    "amount": 10000
}

### Effectuer un transfert
POST {{walletHost}}/api/wallets/transfer
Content-Type: application/json

{
    "senderPhone": "+221779998877",
    "receiverPhone": "+221770000002",
    "amount": 2000
}

### Consulter l'historique des transactions
GET {{walletHost}}/api/wallets/+221779998877/transactions
### Seeder - Créer plusieurs portefeuilles
POST {{walletHost}}/api/wallets/seed?numWallets=5&eventsPerWallet=0
### Consulter les factures impayées du mois en cours
GET {{walletHost}}/api/wallets/external/factures/WLT-0000001/current

### Consulter les factures impayées filtrées par fournisseur
GET {{walletHost}}/api/wallets/external/factures/WLT-0000001/current?unite=ISM

### Consulter les factures impayées sur une période
GET {{walletHost}}/api/wallets/external/factures/WLT-0000001/periode?debut=2026-05-01&fin=2026-07-01

GET {{walletHost}}/api/wallets/+221770000001

GET {{walletHost}}/api/wallets/+221770000001/balance

POST {{walletHost}}/api/wallets
Content-Type: application/json

{
    "phoneNumber": "+221770000001",
    "email": "admin@badwallet.com",
    "initialBalance": 100000,
    "code": "WLT-0000001",
    "currency": "XOF"
}